spring:
  application:
    name: mcp-server
  ai:
    mcp:
      server:
        version: 1.0.0
        name: mcp-server
        type: ASYNC
        instructions: "This server provides internet information tools and resources"
        sse-message-endpoint: /mcp/search/sse
        capabilities:
            tool: true
            resource: true
            prompt: true
            completion: true

server:
  port: 8577
